import Navbar from "@/components/Navbar";
import "./globals.css";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth ">
      <body className="min-h-screen bg-slate-50 dark:bg-black dark:text-white font-serif">
        <Navbar />
        <main className=" mx-auto">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
